config-version: 4

debug: true

storage:
  # MYSQL, SQLITE, YAML
  type: "YAML"
  # Данные ниже заполнять только если используете MySQL
  host: "localhost"
  port: 3306
  database: "treexclans"
  username: "root"
  password: ""
  useSSL: false

# Available serializers:
# LEGACY_AMPERSAND  - "&c&lExample &c&9Text"
# LEGACY_SECTION    - "§c§lExample §c§9Text"
# MINI_MESSAGE      - "<bold><red>Example</red> <blue>Text</blue></bold>"
# GSON              - "[{"text":"Example","bold":true,"color":"red"},{"text":" Text","color":"blue"}]"
# PLAIN             - "Example Text"
# MINIMAL           - &l#RGBExample <#RGB>Text</#RGB>
# UNIFIED - Include all, except GSON
serializer:
  type: UNIFIED
  cache:
    enabled: true
    max-size: 500

clan-storage:
  # Фильтр предметов которых игроки не могут класть в клановый сундук
  filter:
    type: BLACKLIST # BLACKLIST или WHITELIST
    materials:
      - BEDROCK
      - BARRIER


cooldowns:
  # Задержка на приглашение игроку в клан
  invite-expiration: 60
  # Время для подтверждения удаления клана
  disband-expiration: 15
  # Если игрок отклонит запрос клана, то в течении этого срока клан не сможет повторно пригласить
  deny: 120

clan-create:
  ##
  ## Проверки перед созданием клана
  ## Можно добавлять сколько угодно проверок
  ##
  requirements:
    - money-check:
        if: "%vault_eco_balance_fixed% >= 5000"
        then:
          - "[money_take] 5000"
        else:
          - "[message] <#FFE259>&lTreexClans</#FFA751> &7> &cНедостаточно монет! Ваш баланс: &f%vault_eco_balance_fixed%"
  min-clan-tag-length: 3
  max-clan-tag-length: 6
  blocked-tags:
    - "admin"
    - "owner"
    - "op"
  regex: "^[A-Za-z0-9]+$"
  member-rank: MEMBER # ВАЖНО: Укажите здесь ранг, который будет присвоен новому участнику клана при вступлении в клан
  leader-rank: LEADER # ВАЖНО: Укажите здесь ранг, который будет присвоен создателю клана при создании клана


chat-format: "<#FFE259>[Клановый чат]</#FFA751> &6{player} &7▶ &f{message}"

prefix:
  # placeholder %clan_prefix%
  placeholder:
    has_prefix: "&7[&6{prefix}&7]"
    no_prefix: "&8[&e{tag}&8]"
    no_clan: ""
  min-clan-prefix-length: 3
  max-clan-prefix-length: 16
  regex: "^[A-Za-z0-9]+$"
  # какие символы игнорировать из префикса
  length-ignored-symbols: "&x(?:&[0-9A-Fa-f]){6}|&[0-9A-Fa-f]"

slogan:
  min-clan-slogan-length: 3
  max-clan-slogan-length: 64
  regex: "^[A-Za-zА-Яа-яЁё0-9 ]+$"
  # какие символы игнорировать в слогане
  length-ignored-symbols: ""

# placeholder %clan_tag%
tag-placeholder:
  has_clan: "&8[&e{tag}&8]"
  no_clan: ""

ranks:
  # можно создавать сколько угодно рангов
  MEMBER:
    display-name: "&7Участник"
    permissions:
      invite: true
  CONTROL:
    display-name: "&3Управляющий"
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: false
      deposit: true
      withdraw: true
      pvp: true
  LEADER:
    display-name: "&4&lЛидер"
    permissions:
      invite: true
      kick: true
      base: true
      setbase: true
      setrank: true
      deposit: true
      withdraw: true
      pvp: true
      setslogan: true
      setprefix: true
      rename: true


placeholder-show-format: "%weeks% %days% %hours% %minutes%"