<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.jetby.treexclans</groupId>
    <artifactId>Parent</artifactId>
    <version>${pluginVersion}</version>
    <packaging>pom</packaging>

    <properties>
        <pluginVersion>1.0</pluginVersion>
    </properties>
    <modules>
        <module>api</module>
        <module>common</module>
    </modules>

</project>