name: TreexClans
version: '${project.version}'
main: org.jetby.clans.common.TreexClans
api-version: '1.20'
load: POSTWORLD
authors: [ MrJetby ]
website: https://dsc.gg/jmdev
depend:
  - Vault
  - Libb
softdepend:
  - PlaceholderAPI
commands:
  treexclans:
    aliases:
      - tc